
from pydantic import BaseModel, Field


class Requirement(BaseModel):
    id: str = Field(..., description="Unique requirement ID, e.g. RQ-01")
    description: str = Field(..., description="Text description of the requirement")
    cases_count: int = Field(0, description="Total number of test cases covering this requirement")

class ClarifyingQuestion(BaseModel):
    id: str = Field(..., description="Unique question ID, e.g. Q-01")
    requirement_id: str = Field(..., description="Linked requirement ID, e.g. RQ-01")
    question: str = Field(..., description="Question text generated by LLM")

class UserAnswer(BaseModel):
    question_id: str = Field(..., description="ID of the question")
    question: str = Field(..., description="Text of the question")
    answer: str = Field(..., description="Answer provided by user")

class TestScenario(BaseModel):
    id: str = Field(..., description="Unique test case ID, e.g. TC-001")
    name: str = Field(..., description="Test case name")
    priority: str = Field("П2", description="Priority level: П1 (Critical), П2 (Important), П3 (Low)")
    preconditions: list[str] = Field(default_factory=list, description="Preconditions list")
    steps: list[str] = Field(default_factory=list, description="Numbered steps list")
    expected_results: list[str] = Field(default_factory=list, description="Numbered expected results list")
    coverage: list[str] = Field(default_factory=list, description="List of covered requirement IDs (e.g. RQ-01)")

class LLMConfig(BaseModel):
    provider: str = Field("custom", description="LLM provider: 'kaspersky' or 'custom'")
    api_key: str | None = Field(None, description="API Key for Kaspersky LLM")
    base_url: str | None = Field(None, description="Base URL for Kaspersky LLM endpoint")
    model: str | None = Field(None, description="Model name selected by user")

class ModelsRequest(BaseModel):
    provider: str = Field("custom", description="LLM provider: 'kaspersky' or 'custom'")
    api_key: str = Field(..., description="API Key for Kaspersky LLM")
    base_url: str | None = Field(None, description="Base URL for Kaspersky LLM endpoint")

class ModelsResponse(BaseModel):
    models: list[str] = Field(..., description="List of available models")

class AnalysisRequest(BaseModel):
    requirements_text: str
    additional_info: str | None = None
    old_scenarios_text: str | None = None

class RequirementsResponse(BaseModel):
    requirements: list[Requirement]
    is_mock: bool | None = False
    error_message: str | None = None

class QuestionsGenerationRequest(BaseModel):
    requirements: list[Requirement]
    llm_config: LLMConfig | None = None

class QuestionsResponse(BaseModel):
    questions: list[ClarifyingQuestion]
    is_mock: bool | None = False
    error_message: str | None = None

class ScenariosGenerationRequest(BaseModel):
    requirements: list[Requirement]
    answers: list[UserAnswer]
    llm_config: LLMConfig | None = None

class ScenariosResponse(BaseModel):
    scenarios: list[TestScenario]
    is_mock: bool | None = False
    error_message: str | None = None

class CompareRequest(BaseModel):
    old_scenarios_text: str
    new_scenarios: list[TestScenario]
    llm_config: LLMConfig | None = None

class CompareResponse(BaseModel):
    changes_summary: str = Field(..., description="Detailed textual diff/report of changes")
    added: list[str] = Field(default_factory=list, description="List of added scenario IDs")
    removed: list[str] = Field(default_factory=list, description="List of removed scenario IDs")
    modified: list[str] = Field(default_factory=list, description="List of modified scenario IDs")
    is_mock: bool | None = False
    error_message: str | None = None
